### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'is_cuda'

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [mikel-brostrom/Yolov7_StrongSORT_OSNet#29]
Today, I installed this repository and tried to run this model.
But, unfortunetely, the following error occurred.

```
$ python3 track.py --source 0 --yolo-weights yolov7.pt --img 640
/home/********/Yolov7_StrongSORT_OSNet/strong_sort/deep/reid/torchreid/metrics/rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(
Downloading https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt to yolov7.pt...
100%|████████████████████████████████████████████████████████████████████| 72.1M/72.1M [00:08<00:00, 9.31MB/s]

Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
1/1: 0...  success (640x480 at 30.00 FPS).

Traceback (most recent call last):
  File "track.py", line 332, in <module>
    main(opt)
  File "track.py", line 327, in main
    run(**vars(opt))
  File "/home/********/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 112, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride.cpu().numpy())
  File "/home/********/Yolov7_StrongSORT_OSNet/yolov7/utils/datasets.py", line 302, in __init__
    s = np.stack([letterbox(x, self.img_size, stride=self.stride)[0].shape for x in self.imgs], 0)  # shapes
  File "/home/i********/Yolov7_StrongSORT_OSNet/yolov7/utils/datasets.py", line 302, in <listcomp>
    s = np.stack([letterbox(x, self.img_size, stride=self.stride)[0].shape for x in self.imgs], 0)  # shapes
  File "/home/********/Yolov7_StrongSORT_OSNet/yolov7/utils/datasets.py", line 1000, in letterbox
    if stride.is_cuda:
AttributeError: 'numpy.ndarray' object has no attribute 'is_cuda'
terminate called without an active exception
core dump
```
I investigated the past issures and found the same issure.
The issue is saying that bug is fixed.
But, this time the same error occured.
Please fix it.

**Comment by nihanaltaytas** [comment]
i have  the same problem

**Comment by fercod** [comment]
same problem here

**Comment by JakobWl** [comment]
same problem for me too

**Comment by Rizwan2613** [comment]
This issue is occurring in yolov7.  most likely we are cloning some previous branch. @mikel-brostrom needs to change the submodule file as yolov7 is cloning outdated code, causing this issue. Alternatively,  you can edit the dataset.py file located at 'yolov7/utils/datasets.py' and delete following lines (line 1000 and 1001):

```
    if stride.is_cuda:
        stride = stride.cpu().numpy()
```

**Comment by Ishihara-Masabumi** [comment]
Thanks!

**Comment by mikel-brostrom** [comment]
Submodule updated and fixed some minor stuff as well :smile:

**Comment by mikel-brostrom** [comment]
Could somebody try it out and report back here @JakobWl , @fercod , @nihanaltaytas ?

**Comment by Ishihara-Masabumi** [comment]
That's OK, thanks.
